version: '3'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: metastore_db
            POSTGRES_USER: hive
            POSTGRES_PASSWORD: mypass
    hive-metastore:
        image: someregistry.azurecr.io/hive-metastore:3.1.2
        restart: always
        volumes:
            - ./conf:/opt/hive/conf
        depends_on:
            - db
    trino:
        image: mytrino
        build:
            context: .
            dockerfile: Dockerfile.trino
        ports:
            - 8080:8080